datadogconfig:
  apiKey: "![jjHK4sRZFLK+V2hZwx8pNAusNVJqeBjNx9/XPCFfGVkP5YA8R0d+Rg==]"
  #apiKey: "![VA768BbcRsGjwm5KzykTTea0UIQz3nzwk9XNYuI0u4CqnEaMltUwDQ==]"
  
helloPackage:
  key: "![nd2EXUocuGYmcc1dt87xvAR91diJIxWtrKy/LifuXW8=]"